version: '3.1' #minimum v2

services:
  drupal: 
    image: drupal
    volumes: 
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles 
      - drupal-sites:/var/www/html/sites 
      - drupal-themes:/var/www/html/themes 
    ports:
      - 8080:80
    depends_on: 
      - postgres

  postgres:
    image: postgres
    environment: 
      - POSTGRES_DB=drupal
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal


volumes: 
  drupal-modules:
  drupal-profiles:
  drupal-sites: 
  drupal-themes:
